-- ============================================================
-- Project: Hospital Appointments & Patient Care Analysis
-- Script: 01_schema.sql
-- Purpose: Create the relational schema for a hospital
--          appointment analysis database.
-- Database: hospital_db
-- ============================================================

-- The model follows a dimensional approach:
-- 1 fact table: fact_appointments
-- 5 dimension tables: patients, doctors, specialties, hospitals and dates.

-- Fact table granularity:
-- One row represents one medical appointment between one patient
-- and one doctor on one specific date.

-- Drop existing tables to allow the script to be executed from scratch.
-- Fact tables are dropped first because they depend on dimension tables.



DROP TABLE IF EXISTS fact_appointments CASCADE;
DROP TABLE IF EXISTS dim_dates CASCADE;
DROP TABLE IF EXISTS dim_hospitals CASCADE;
DROP TABLE IF EXISTS dim_specialties CASCADE;
DROP TABLE IF EXISTS dim_patients CASCADE;
DROP TABLE IF EXISTS dim_doctors CASCADE;


-- ============================================================
-- 1. DIMENSION TABLES
-- ============================================================

-- Dimension Table: Patients
-- Purpose: Stores demographic and insurance information about patients.
--
-- Primary Key:
-- patient_id uniquely identifies each patient.
--
-- Constraints:
-- - first_name and last_name cannot be NULL.
-- - gender is restricted to valid values.
-- - insurance_type is restricted to valid values.
-- ============================================================

CREATE TABLE dim_patients (
    patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Automatically generates the id
    first_name VARCHAR(50) NOT NULL, -- Is not valid without a name 
    last_name VARCHAR(50) NOT NULL,-- Is not valid without a last name
    gender VARCHAR(10)
        CHECK (gender IN ('Male', 'Female', 'Other')),
    birth_date DATE NOT NULL,
    city VARCHAR(100),
    insurance_type VARCHAR(20)
        CHECK (insurance_type IN ('Public', 'Private', 'None')),
    registration_date DATE -- Date when the patient registered in the system
);



-- Dimension Table: Specialties
-- Stores medical specialties.
--
-- Primary Key:
-- speciality_id uniquely identifies each speciality.
--
-- Each specialty can be assigned to many doctors.
-- ============================================================

CREATE TABLE dim_specialties (
    specialty_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    specialty_name VARCHAR(100) UNIQUE NOT NULL
);



-- Dimension Table: dim_hospital
-- Stores information about hospitals.
--
-- Primary Key:
-- hospital_id uniquely identifies each hospital.
--
-- Constraints:
-- hospital_name is UNIQUE because two hospitals should not to share the same name.
-- hospital_type is restricted to valid business categories.
-- ============================================================

CREATE TABLE dim_hospitals (
	hospital_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	hospital_name VARCHAR(100) UNIQUE NOT NULL,
	city VARCHAR(100) NOT NULL,
	region VARCHAR(100) NOT NULL,
	hospital_type VARCHAR(50)
		CHECK (hospital_type IN ('Public','Private', 'University'))
);



-- Dimension Table: dim_doctors
-- Stores doctors and links each doctor to one specialty and one hospital.
--
-- Primary Key:
-- doctor_id uniquely identifies each doctor.
--
-- Constraints:
-- first_name and last_name are mandatory.
-- is_active defaults to TRUE.
-- ============================================================

CREATE TABLE dim_doctors(
	doctor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	specialty_id INTEGER NOT NULL,
	hospital_id INTEGER NOT NULL,
	first_name VARCHAR(20) NOT NULL,
	last_name VARCHAR(20) NOT NULL,
	hire_date DATE,
	is_active BOOLEAN DEFAULT TRUE,
	CONSTRAINT fk_doctors_specialty
        FOREIGN KEY (specialty_id) REFERENCES dim_specialties(specialty_id),
	CONSTRAINT fk_doctors_hospital
        FOREIGN KEY (hospital_id) REFERENCES dim_hospitals(hospital_id)
);



-- Dimension Table: Dates
-- Purpose: Stores calendar information to support time-based analysis.
--
-- Primary Key:
-- date_id uniquely identifies each date.
--
-- Constraints:
-- full_date is UNIQUE because each calendar date should appear only once.
-- month has to be a number between 1 and 12.
-- quarter has to be a number between 1 and 4. 
-- ============================================================

CREATE TABLE dim_dates(
	date_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	full_date DATE UNIQUE NOT NULL,
	year INTEGER NOT NULL,
	month INTEGER NOT NULL
		CHECK (month BETWEEN 1 AND 12),
	month_name VARCHAR(20) NOT NULL,
	quarter INTEGER NOT NULL
		CHECK (quarter BETWEEN 1 AND 4),
	day_of_week VARCHAR(20) NOT NULL
);

-- ============================================================
-- 2. FACT TABLE
-- ============================================================

-- Fact Table: Appointments
-- Purpose: Stores medical appointment events.
-- Granularity: One row represents one appointment between one patient and one doctor on one specific date.
-- Some columns allow NULL because cancelled, no-show or scheduled appointments may not have fee, waiting time, duration or satisfaction.
--
-- Foreign Keys:
-- patient_id references dim_patients.
-- doctor_id references dim_doctors.
-- date_id references dim_dates.
--
-- Constraints:
-- appointment_status is restricted to valid appointment states.
-- consultation_fee cannot be negative.
-- waiting_minutes cannot be negative.
-- appointment_duration_minutes must be positive.
-- satisfaction_score must be between 1 and 5.
-- ============================================================

CREATE TABLE fact_appointments(
	appointment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	patient_id INTEGER NOT NULL,
	doctor_id INTEGER NOT NULL,
	date_id INTEGER NOT NULL,
	appointment_status VARCHAR(20) NOT NULL 
		CHECK (appointment_status IN ('Completed', 'Cancelled', 'No-show','Scheduled')),
	consultation_fee NUMERIC(10,2), -- We don't use `NOT NULL` because we'll need `NULL` for canceled appointments.
	waiting_minutes INTEGER
		CHECK (waiting_minutes >= 0),
	appointment_duration_minutes INTEGER
		CHECK(appointment_duration_minutes > 0),
	satisfaction_score INTEGER 
		CHECK (satisfaction_score BETWEEN 1 AND 5),
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_appointments_patient
        FOREIGN KEY (patient_id) REFERENCES dim_patients(patient_id),
    CONSTRAINT fk_appointments_doctor
        FOREIGN KEY (doctor_id) REFERENCES dim_doctors(doctor_id),
    CONSTRAINT fk_appointments_date
        FOREIGN KEY (date_id) REFERENCES dim_dates(date_id)
	);


-- ============================================================
-- 2. INDEX
-- ============================================================

-- Index
-- Purpose: Improves performance for queries filtering or grouping appointments by doctor and dates 
-- because it's probably to use a lot of queries where we need filter by doctor_id and date_id.
-- ============================================================

CREATE INDEX idx_fact_appointments_doctor_id 
ON fact_appointments(doctor_id);

CREATE INDEX idx_fact_appointments_date_id
ON fact_appointments(date_id);



-- ============================================================
-- 3. VIEWS
-- ============================================================

-- View: appointment_details
--
-- Purpose: Provides a view combining appointments information with patients, doctors and specialties.


DROP VIEW IF EXISTS appointment_details;
CREATE VIEW appointment_details AS
SELECT
    fa.appointment_id,
    h.hospital_name,
    p.first_name || ' ' || p.last_name AS patient,
    d.first_name || ' ' || d.last_name AS doctor,
    sp.specialty_name,
    da.full_date,
    fa.appointment_status,
    fa.consultation_fee,
    fa.waiting_minutes,
    fa.appointment_duration_minutes,
    fa.satisfaction_score
FROM fact_appointments fa
INNER JOIN dim_patients p ON fa.patient_id = p.patient_id
INNER JOIN dim_doctors d ON fa.doctor_id = d.doctor_id
INNER JOIN dim_specialties sp ON d.specialty_id = sp.specialty_id
INNER JOIN dim_dates da ON fa.date_id = da.date_id
INNER JOIN dim_hospitals h ON d.hospital_id =  h.hospital_id;




-- View: doctor_performance
--
-- Purpose: Provides info and details by doctors.

DROP VIEW IF EXISTS doctor_performance;
CREATE VIEW doctor_performance AS
SELECT
    d.doctor_id,
    d.first_name || ' ' || d.last_name AS doctor_name,
    COUNT(fa.appointment_id) AS total_appointments,
    COALESCE(AVG(fa.satisfaction_score),0) AS avg_satisfaction,
    COALESCE(SUM(fa.consultation_fee),0) AS total_revenue
FROM dim_doctors d
LEFT JOIN fact_appointments fa ON d.doctor_id = fa.doctor_id
GROUP BY d.doctor_id;




-- View: doctor_performance
--
-- Purpose: Provides info and details by hospitals. To answer the following question: For each hospital  what is the number of appointments and average satisfaction?

DROP VIEW IF EXISTS hospital_details;
CREATE VIEW hospital_details AS
SELECT 
	h.hospital_id,
	h.hospital_name,
	COUNT(CASE WHEN fa.appointment_status = 'Completed' THEN 1 END) AS completed_appointments,
	ROUND(AVG(fa.satisfaction_score),2) AS avg_satisfaction_score,
	SUM(fa.consultation_fee) AS total_revenue
FROM dim_hospitals h
LEFT JOIN dim_doctors d ON h.hospital_id = d.hospital_id
LEFT JOIN fact_appointments fa ON d.doctor_id = fa.doctor_id
GROUP BY h.hospital_id;



-- ============================================================
-- 4. FUNCTION
-- ============================================================

-- Function: get_doctor_revenue
-- Purpose: Returns the total revenue generated by a specific doctor.

CREATE OR REPLACE FUNCTION get_doctor_revenue(p_doctor_id INTEGER)
RETURNS NUMERIC AS $$
    SELECT
        COALESCE(SUM(consultation_fee), 0) -- If SUM is NULL it returns 0.
    FROM fact_appointments
    WHERE doctor_id = p_doctor_id AND appointment_status = 'Completed';
$$ LANGUAGE SQL;



